name: Scully Publish to GH-Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    env:
      BASE_HREF: /poptech2/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cmgriffing/scully-gh-pages-action@v9
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          build-args: --stats-json
          scully-args: --scanRoutes --configFile ./scully.popsuite-site.config.prod.ts
